### PR TITLE
0.2.1 bugfix and hudbars

### PR DESCRIPTION
**Pull request by berengma**
This fixes two crashes: the crash onleaveplayer bug and the other is a missing nil check in torches

This introduces wuzzy's hudbars for thirst, hunger, energy and body temp.
Also adds a text hud saying the outside environment temperature.

It is online in 3xile if you want to see it :)

### CODE REVIEW

**Comment by DokimiCU** [comment]
I've opened a  Development branch which is were pull requests should go
 (so I don't confuse myself. I have a terrible habit of creating many branches for old updates ... I didn't know how to do releases! I have no idea what I'm doing basically...)



Once I've played with HUD bars on, I'll decide if I like it.



crash onleaveplayer bug:
I'm not familiar with this bug, how does this fix it?
--lay_down(player, nil, nil, false, true)

**Comment by berengma** [comment]
> crash onleaveplayer bug:
> I'm not familiar with this bug, how does this fix it?
> --lay_down(player, nil, nil, false, true)

it does not. See "the real fix for onleaveplayer bug".
There I commented out the whole register_on_leaveplayer thing.
If you do not, server will crash each time only one player leaves the game.

**Comment by berengma** [comment]
I changed the base to Development.

**Comment by DokimiCU** [comment]
crash onleaveplayer bug:

The beds code was adapted from Minetest Game, I'm guessing onleaveplayer was in there for a reason?? Just removing it doesn't break anything?? e.g the "Break time" reminder.

I'm happy to merge bug fixes, but not yet convinced by Wuzzy's Hud Bars. Exile's needs might be a bit different than what it was designed for.

You have raised a legitimate issue that HUD needs improving though.

**Comment by berengma** [comment]
> crash onleaveplayer bug:
> 
> The beds code was adapted from Minetest Game, I'm guessing onleaveplayer was in there for a reason?? Just removing it doesn't break anything?? e.g the "Break time" reminder.

No this is all working. break time reminder is still showing when you want to lay down.

> 
> I'm happy to merge bug fixes, but not yet convinced by Wuzzy's Hud Bars. Exile's needs might be a bit different than what it was designed for.

It fits to the health and breath bar and gives valuable information to the players. But any other hud would do that, too.
That is right. Up to you. I only experienced that most players on the server were confused with the old hud.

**Pull request closed without merging**
